# Generated by Django 3.2.7 on 2021-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=32)),
                ('autor', models.CharField(max_length=64)),
                ('data_publikacji', models.DateField()),
                ('numer_ISBN', models.CharField(max_length=17)),
                ('liczba_stron', models.IntegerField()),
                ('link_do_okladki', models.URLField()),
                ('jezyk_publikacji', models.CharField(max_length=32)),
            ],
        ),
    ]
