# Generated by Django 3.2.7 on 2021-09-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numer_ISBN',
            new_name='ISBN_number',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='data_publikacji',
            new_name='date_of_publication',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='jezyk_publikacji',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='link_do_okladki',
            new_name='link_to_cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='liczba_stron',
            new_name='number_of_pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='tytul',
            new_name='title',
        ),
    ]
