# Generated by Django 3.2.7 on 2021-10-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210930_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='link_to_cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True),
        ),
    ]
