# Generated by Django 3.2.7 on 2021-10-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20211004_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(),
        ),
    ]
