# Generated by Django 3.2.7 on 2021-10-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(null=True),
        ),
    ]
