# Generated by Django 3.2.7 on 2021-10-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN_number',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
